# Generated by Django 5.2.16 on 2026-07-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_procurementauditevent'),
        ('tenants', '0004_tenantmembership_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='attachment',
            field=models.FileField(blank=True, upload_to='tenders/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tender',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.CharField(choices=[('works', 'Works / construction'), ('goods', 'Goods / supplies'), ('services', 'Professional services')], default='works', max_length=20),
        ),
        migrations.AddField(
            model_name='tender',
            name='clarification_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tender',
            name='contact_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='tender',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='tenders/covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tender',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AddField(
            model_name='tender',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='tenants.department'),
        ),
        migrations.AddField(
            model_name='tender',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='evaluation_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_method',
            field=models.CharField(choices=[('open', 'Open competition'), ('limited', 'Limited competition'), ('rfq', 'Request for quotations')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='tender',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='tenants.servicearea'),
        ),
        migrations.AddField(
            model_name='tender',
            name='submission_instructions',
            field=models.TextField(blank=True),
        ),
    ]
