# Generated by Django 5.2.16 on 2026-07-29 12:27

import apps.tenants.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(help_text='Stable identifier used in tenant-scoped URLs and integrations.', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending setup'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('timezone', models.CharField(default='UTC', help_text='IANA timezone, for example Asia/Karachi.', max_length=64, validators=[apps.tenants.models.validate_timezone])),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='tenant_slug_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='Tenant-unique short code, for example ROADS or WASTE.', max_length=30, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, hyphens, or underscores, starting with a letter or number.', regex='^[A-Za-z0-9][A-Za-z0-9_-]*$')])),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant__name', 'name'),
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='dept_tenant_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('tenant'), name='dept_tenant_code_ci_unique')],
            },
        ),
    ]
