# Generated by Django 5.2.16 on 2026-07-29 12:47

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(help_text='Tenant-unique short code, for example CENTRAL or NORTH-01.', max_length=30, validators=[django.core.validators.RegexValidator(message='Use letters, numbers, hyphens, or underscores, starting with a letter or number.', regex='^[A-Za-z0-9][A-Za-z0-9_-]*$')])),
                ('description', models.TextField(blank=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='The supported boundary in WGS 84 coordinates.', srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_areas', to='tenants.tenant')),
            ],
            options={
                'ordering': ('tenant__name', 'name'),
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='area_tenant_active_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('tenant'), name='area_tenant_code_ci_unique')],
            },
        ),
    ]
